services:
  - type: web
    name: linkedin-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: LINKEDIN_EMAIL
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false
    healthCheckPath: /
    plan: starter

